### PR TITLE
#50: Max rows not working with text without breakline char (closes #50)

### LINKED ISSUE #50: Max rows not working with text without breakline char
Max-rows not work with long strings:
```
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga aspernatur ut ullam rem ipsam. Fuga illo velit sapiente necessitatibus, voluptatum earum at quo magnam impedit, molestias aliquid, voluptates, sit odit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga aspernatur ut ullam rem ipsam. Fuga illo velit sapiente necessitatibus, voluptatum earum at quo magnam impedit, molestias aliquid, voluptates, sit odit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga aspernatur ut ullam rem ipsam. Fuga illo velit sapiente necessitatibus, voluptatum earum at quo magnam impedit, molestias aliquid, voluptates, sit odit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga aspernatur ut ullam rem ipsam. Fuga illo velit sapiente necessitatibus, voluptatum earum at quo magnam impedit, molestias aliquid, voluptates, sit odit.
```
Bug example:
image

### PR DESCRIPTION
**Pull request by FrancescoCioria**
Closes #50

### tests performed
- maxRows=3 and current examples -> it works
- maxRows=3 and broken example from issue -> it works
- maxRows=5 and broken example from issue then, after 3 seconds change it 3 -> it works and it updates

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

### CODE REVIEW

File: src/TextareaAutosize.js [hunk 1]
```diff
@@ -21,20 +22,19 @@ export default class TextareaAutosize extends React.Component {
...
-    if (this.hasReachedMaxRows(value || defaultValue)) {
-      this.updateMaxHeight(value || defaultValue);
+    if (typeof maxRows === 'number') {
+      this.updateLineHeight();
 
       // this trick is needed to force "autosize" to activate the scrollbar
-      this.dispatchEvent(DESTROY);
       setTimeout(() => autosize(this.textarea));
+    } else {
+      autosize(this.textarea);
```
Comment (giogonzo) [inline src/TextareaAutosize.js]: this is a bit obscure.. why no `DESTROY` anymore and a sync (no `setTimeout`) `autosize()` here?

Comment (FrancescoCioria) [inline src/TextareaAutosize.js]: the async `autosize` is needed as before to wait for `maxHeight` to be used, otherwise you wouldn't see the scrollbar and wouldn't be able to scroll.

The reason I removed the `DESTROY` is because I realized that I could avoid the first `autosize` completely when we have to `maxRows` as we're re-doing it anyway so I replaced the `DESTROY` with an `else`
