### PR TITLE
#48: linked module fails to load in webpack (closes #48)

### LINKED ISSUE #48: linked module fails to load in webpack
Hi,

I tried to link the `react-autosize-textarea`  module in my project (npm link) to debug some issue but it failed with the error that `lib` cannot be found. I traced the failure to the `react-autosize-textarea/index.js` where `require()` is called without the leading './' which causes the loader to search for lib in node_modules.  Once the leading './' is added everything seems to work.

### PR DESCRIPTION
**Pull request by FrancescoCioria**
Closes #48

### tests performed
- improve import in test -> tests fail
- fix `index.js` -> tests pass once again

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

### CODE REVIEW

File: test/tests/TextareaAutosize-test.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import React from 'react';
 import TestUtils from 'react-dom/test-utils';
 import expect from 'expect';
-import TextareaAutosize from '../../lib';
+import TextareaAutosize from '../../index';
```
Comment (giogonzo) [inline test/tests/TextareaAutosize-test.js]: minor, but could be just `../../`?

Comment (FrancescoCioria) [inline test/tests/TextareaAutosize-test.js]: yes, I wanted to be explicit
